services:
  mongo:
    image: mongo:7.0.5
    container_name: product_service_mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - mongo_data:/data/db


volumes:
  mongo_data: