services:
  mysql:
    image: mysql:8.0.34
    container_name: payment_service_mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: payment-service
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: